In [11]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [12]:
data = pd.read_csv('Iris.csv')

In [13]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [14]:
data.head(2)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

In [17]:
x = data.iloc[:, :-1]

In [18]:
y = data.iloc[:, -1]

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

print (x_train[0:10, :])

[[-1.21030717 -1.47393679  1.22037928 -1.5639872  -1.30948358]
 [-1.37240188 -0.13307079  3.02001693 -1.27728011 -1.04292204]
 [-0.21458252  1.08589829  0.09560575  0.38562104  0.28988568]
 [-1.46502743 -1.23014297  0.77046987 -1.21993869 -1.30948358]
 [-0.74717943 -1.7177306   0.32056046 -1.39196294 -1.30948358]
 [ 1.66108484  0.59831066 -1.25412249  0.72966956  0.95628954]
 [-0.53877194  0.72020757  0.32056046  0.44296246  0.42316645]
 [-1.09452523 -0.74255534  0.99542457 -1.27728011 -1.30948358]
 [-1.62712214 -0.98634915  1.22037928 -1.33462153 -1.30948358]
 [-0.9787433  -0.74255534  2.34515281 -1.27728011 -1.44276436]]


In [25]:
model = LogisticRegression(random_state = 0)
model.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [26]:
predictions = model.predict(x_test)

In [27]:
print(predictions)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']


In [28]:
print (classification_report(y_test, predictions) )

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [29]:
print (accuracy_score(y_test, predictions))

1.0


In [30]:
from ydata_profiling import ProfileReport
b = ProfileReport(data)
b.to_file('flowerReport.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [32]:
sns.swarmplot(x="Species",y="PetalLengthCm",data=data)

<Axes: xlabel='Species', ylabel='PetalLengthCm'>