In [1]:
import numpy as np
import pandas as pd

# a. Create a numpy array with values from 1 to 20.
numpy_array = np.arange(1, 21)

In [2]:
print(numpy_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# b. Reshape it to a 4 x 5 two-dimensional array.
reshaped_array = numpy_array.reshape(4, 5)

In [4]:
print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# c. Convert it into a pandas data frame.
data_frame = pd.DataFrame(reshaped_array, columns=['Col1', 'Col2', 'Col3', 'Col4', 'Col5'])

In [7]:
data_frame.head(3)

Col1  Col2  Col3  Col4  Col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15